import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Root from "@/components/root";
import RQProviders from "./react-query-providers";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <RQProviders>
          <Root>{children}</Root>
        </RQProviders>
      </body>
    </html>
  );
}
