import type { Metadata } from "next";
import { Lato } from "next/font/google";
import Root from "@/components/root";
import RQProviders from "./react-query-providers";
import "./globals.css";

const lato = Lato({
  weight: ["100", "300", "400", "700", "900"],
  subsets: ["latin-ext"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={lato.className}>
        <RQProviders>
          <Root>{children}</Root>
        </RQProviders>
      </body>
    </html>
  );
}
